"""baseline esquema trivia

Revision ID: 4bbfb7c3085b
Revises: 
Create Date: 2026-06-16 15:51:41.912338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bbfb7c3085b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('nombre_evento', sa.String(length=255), nullable=False),
    sa.Column('tipo_evento', sa.Enum('TRIVIA_GENERAL', 'SORTEO_GENERAL', name='tipo_evento', schema='trivia'), nullable=False),
    sa.PrimaryKeyConstraint('id_evento'),
    sa.UniqueConstraint('nombre_evento'),
    schema='trivia'
    )
    op.create_index(op.f('ix_trivia_eventos_id_evento'), 'eventos', ['id_evento'], unique=False, schema='trivia')
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('cedula', name='uq_usuario_cedula'),
    schema='trivia'
    )
    op.create_index(op.f('ix_trivia_usuarios_cedula'), 'usuarios', ['cedula'], unique=True, schema='trivia')
    op.create_index(op.f('ix_trivia_usuarios_id_usuario'), 'usuarios', ['id_usuario'], unique=False, schema='trivia')
    op.create_table('grupos',
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('nombre_grupo', sa.String(length=255), nullable=False),
    sa.Column('fecha_inicio', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fecha_cierre', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('max_intentos', sa.SmallInteger(), nullable=False),
    sa.Column('cooldown', sa.Interval(), nullable=False),
    sa.CheckConstraint("cooldown >= interval '0 seconds'", name='ck_cooldown'),
    sa.CheckConstraint('fecha_cierre > fecha_inicio', name='ck_fecha'),
    sa.CheckConstraint('max_intentos > 0', name='ck_max_intentos'),
    sa.ForeignKeyConstraint(['id_evento'], ['trivia.eventos.id_evento'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_grupo'),
    sa.UniqueConstraint('id_evento', 'nombre_grupo'),
    schema='trivia'
    )
    op.create_index(op.f('ix_trivia_grupos_id_grupo'), 'grupos', ['id_grupo'], unique=False, schema='trivia')
    op.create_table('secciones',
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('nombre_seccion', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['trivia.eventos.id_evento'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_seccion'),
    sa.UniqueConstraint('id_evento', 'nombre_seccion'),
    schema='trivia'
    )
    op.create_index(op.f('ix_trivia_secciones_id_seccion'), 'secciones', ['id_seccion'], unique=False, schema='trivia')
    op.create_table('participaciones',
    sa.Column('id_participacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('numero_intento', sa.SmallInteger(), nullable=False),
    sa.Column('respuestas_usuario', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('respuestas_abiertas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'FINALIZADO', name='estado_participacion', schema='trivia'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tiempo_total', sa.Interval(), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo'], ['trivia.grupos.id_grupo'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['trivia.usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_participacion'),
    sa.UniqueConstraint('id_usuario', 'id_grupo', 'numero_intento', name='uq_usuario_grupo_intento'),
    schema='trivia'
    )
    op.create_index(op.f('ix_trivia_participaciones_id_participacion'), 'participaciones', ['id_participacion'], unique=False, schema='trivia')
    op.create_table('preguntas',
    sa.Column('id_pregunta', sa.Integer(), nullable=False),
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('tipo_pregunta', sa.Text(), nullable=False),
    sa.Column('opcion_correcta', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_seccion'], ['trivia.secciones.id_seccion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_pregunta'),
    sa.UniqueConstraint('id_seccion', 'pregunta', name='uq_seccion_pregunta'),
    schema='trivia'
    )
    op.create_index(op.f('ix_trivia_preguntas_id_pregunta'), 'preguntas', ['id_pregunta'], unique=False, schema='trivia')
    op.create_table('respuestas',
    sa.Column('id_respuesta', sa.Integer(), nullable=False),
    sa.Column('id_pregunta', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.CheckConstraint('orden > 0'),
    sa.ForeignKeyConstraint(['id_pregunta'], ['trivia.preguntas.id_pregunta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_respuesta'),
    sa.UniqueConstraint('id_pregunta', 'orden'),
    schema='trivia'
    )
    op.create_index(op.f('ix_trivia_respuestas_id_respuesta'), 'respuestas', ['id_respuesta'], unique=False, schema='trivia')
    op.create_table('respuestas_usuarios',
    sa.Column('id_respuesta_usuario', sa.Integer(), nullable=False),
    sa.Column('id_participacion', sa.Integer(), nullable=False),
    sa.Column('id_pregunta', sa.Integer(), nullable=False),
    sa.Column('orden_seleccionado', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_participacion'], ['trivia.participaciones.id_participacion'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pregunta'], ['trivia.preguntas.id_pregunta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_respuesta_usuario'),
    sa.UniqueConstraint('id_participacion', 'id_pregunta', name='uq_participacion_pregunta'),
    schema='trivia'
    )
    op.create_index(op.f('ix_trivia_respuestas_usuarios_id_respuesta_usuario'), 'respuestas_usuarios', ['id_respuesta_usuario'], unique=False, schema='trivia')
    op.create_table('resultados',
    sa.Column('id_resultado', sa.Integer(), nullable=False),
    sa.Column('id_participacion', sa.Integer(), nullable=False),
    sa.Column('total_preguntas', sa.Integer(), nullable=False),
    sa.Column('respuestas_correctas', sa.Integer(), nullable=False),
    sa.Column('respuestas_incorrectas', sa.Integer(), nullable=False),
    sa.Column('porcentaje_acierto', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tiempo_total', sa.Interval(), nullable=False),
    sa.ForeignKeyConstraint(['id_participacion'], ['trivia.participaciones.id_participacion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_resultado'),
    sa.UniqueConstraint('id_participacion', name='uq_resultado_participacion'),
    schema='trivia'
    )
    op.create_index(op.f('ix_trivia_resultados_id_resultado'), 'resultados', ['id_resultado'], unique=False, schema='trivia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trivia_resultados_id_resultado'), table_name='resultados', schema='trivia')
    op.drop_table('resultados', schema='trivia')
    op.drop_index(op.f('ix_trivia_respuestas_usuarios_id_respuesta_usuario'), table_name='respuestas_usuarios', schema='trivia')
    op.drop_table('respuestas_usuarios', schema='trivia')
    op.drop_index(op.f('ix_trivia_respuestas_id_respuesta'), table_name='respuestas', schema='trivia')
    op.drop_table('respuestas', schema='trivia')
    op.drop_index(op.f('ix_trivia_preguntas_id_pregunta'), table_name='preguntas', schema='trivia')
    op.drop_table('preguntas', schema='trivia')
    op.drop_index(op.f('ix_trivia_participaciones_id_participacion'), table_name='participaciones', schema='trivia')
    op.drop_table('participaciones', schema='trivia')
    op.drop_index(op.f('ix_trivia_secciones_id_seccion'), table_name='secciones', schema='trivia')
    op.drop_table('secciones', schema='trivia')
    op.drop_index(op.f('ix_trivia_grupos_id_grupo'), table_name='grupos', schema='trivia')
    op.drop_table('grupos', schema='trivia')
    op.drop_index(op.f('ix_trivia_usuarios_id_usuario'), table_name='usuarios', schema='trivia')
    op.drop_index(op.f('ix_trivia_usuarios_cedula'), table_name='usuarios', schema='trivia')
    op.drop_table('usuarios', schema='trivia')
    op.drop_index(op.f('ix_trivia_eventos_id_evento'), table_name='eventos', schema='trivia')
    op.drop_table('eventos', schema='trivia')
    # ### end Alembic commands ###
