"""indices en FKs para acelerar consultas (participaciones grupo/estado, respuestas_usuarios pregunta)

Revision ID: c4790951b3ab
Revises: ead95424665b
Create Date: 2026-06-16 23:10:15.134800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4790951b3ab'
down_revision: Union[str, Sequence[str], None] = 'ead95424665b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_trivia_participaciones_estado'), 'participaciones', ['estado'], unique=False, schema='trivia')
    op.create_index(op.f('ix_trivia_participaciones_id_grupo'), 'participaciones', ['id_grupo'], unique=False, schema='trivia')
    op.create_index(op.f('ix_trivia_respuestas_usuarios_id_pregunta'), 'respuestas_usuarios', ['id_pregunta'], unique=False, schema='trivia')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trivia_respuestas_usuarios_id_pregunta'), table_name='respuestas_usuarios', schema='trivia')
    op.drop_index(op.f('ix_trivia_participaciones_id_grupo'), table_name='participaciones', schema='trivia')
    op.drop_index(op.f('ix_trivia_participaciones_estado'), table_name='participaciones', schema='trivia')
    # ### end Alembic commands ###
