"""secciones por grupo (id_grupo) + FK compuesto y unique en grupos

Revision ID: ead95424665b
Revises: 4bbfb7c3085b
Create Date: 2026-06-16 15:57:59.570106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead95424665b'
down_revision: Union[str, Sequence[str], None] = '4bbfb7c3085b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_grupo_evento_id', 'grupos', ['id_evento', 'id_grupo'], schema='trivia')
    op.add_column('secciones', sa.Column('id_grupo', sa.Integer(), nullable=True), schema='trivia')
    op.drop_constraint(op.f('secciones_id_evento_nombre_seccion_key'), 'secciones', schema='trivia', type_='unique')
    op.create_index('uq_seccion_evento_comun', 'secciones', ['id_evento', 'nombre_seccion'], unique=True, schema='trivia', postgresql_where=sa.text('id_grupo IS NULL'))
    op.create_index('uq_seccion_evento_grupo', 'secciones', ['id_evento', 'id_grupo', 'nombre_seccion'], unique=True, schema='trivia', postgresql_where=sa.text('id_grupo IS NOT NULL'))
    op.create_foreign_key('fk_seccion_evento_grupo', 'secciones', 'grupos', ['id_evento', 'id_grupo'], ['id_evento', 'id_grupo'], source_schema='trivia', referent_schema='trivia', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_seccion_evento_grupo', 'secciones', schema='trivia', type_='foreignkey')
    op.drop_index('uq_seccion_evento_grupo', table_name='secciones', schema='trivia', postgresql_where=sa.text('id_grupo IS NOT NULL'))
    op.drop_index('uq_seccion_evento_comun', table_name='secciones', schema='trivia', postgresql_where=sa.text('id_grupo IS NULL'))
    op.create_unique_constraint(op.f('secciones_id_evento_nombre_seccion_key'), 'secciones', ['id_evento', 'nombre_seccion'], schema='trivia')
    op.drop_column('secciones', 'id_grupo', schema='trivia')
    op.drop_constraint('uq_grupo_evento_id', 'grupos', schema='trivia', type_='unique')
    # ### end Alembic commands ###
