name: Build and deploy Python app to Azure Container Apps - TriviaAPI

on:
  # Solo se activa automáticamente si haces push a un tag
  push:
    tags:
      - 'v*'
      - 'rollback-*'

  # Permitir ejecución manual desde GitHub Actions
  workflow_dispatch:
    inputs:
      ref_to_deploy:
        description: 'Nombre de la rama o tag a desplegar (ej: master, release/v1.0.0, rollback-v1.0.1)'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout del código desde tag o rama
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref_to_deploy || github.ref }}

      - name: Login en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7C2A4F5F47CE4FF484F9F9EDC176F995 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E97780AF6AF34E02AFE37FC104AFA7C5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_385A573DD35449EDAFC949420786C4A3 }}

      - name: Login en Azure Container Registry
        run: az acr login --name triviaapiacr

      - name: Build y push de la imagen
        run: |
          IMAGE_TAG=triviaapiacr.azurecr.io/trivia-api:${{ github.sha }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Deploy a Azure Container Apps
        run: |
          az containerapp update \
            --name trivia-api \
            --resource-group Soporte \
            --image $IMAGE_TAG
