name: Build and deploy Python app to Azure Web App - TriviaAPI

on:
  # Solo se activa automáticamente si haces push a un tag
  push:
    tags:
      - 'v*'
      - 'rollback-*'

  # Permitir ejecución manual desde GitHub Actions
  workflow_dispatch:
    inputs:
      ref_to_deploy:
        description: 'Nombre de la rama o tag a desplegar (ej: master, release/v1.0.0, rollback-v1.0.1)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout del código desde tag o rama
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref_to_deploy || github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Crear y activar entorno virtual
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Comprimir artefacto para despliegue
        run: zip release.zip ./* -r

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Descomprimir artefacto
        run: unzip release.zip

      - name: Login en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7C2A4F5F47CE4FF484F9F9EDC176F995 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E97780AF6AF34E02AFE37FC104AFA7C5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_385A573DD35449EDAFC949420786C4A3 }}

      - name: Desplegar a Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'TriviaAPI'
          slot-name: 'Production'